### ISSUE TITLE
File format not accepted for GWAS file 

### ISSUE THREAD

**Issue by rikomiko** [jianyanglab/SMR-Portal#1]
Hi there,

Thank you for creating a wonderful tool to perform SMR analyses. 

I am having trouble uploading my Crohn's disease GWAS dataset, downloaded from [here](https://www.nature.com/articles/s41588-023-01384-0#:~:text=Inflammatory%20bowel%20diseases%20(IBDs)%20are%20chronic), then organised into GCTA-COJO format, see below. 

```
cd <- read.table("cd_eur_v4_fil_cojo.txt", header = T, row.names = NULL)
> head(cd)
          SNP A1 A2    frq       b     se        P      N
1  rs58276399  c  t 0.1311 -0.0523 0.0236 0.026620 367592
2  rs12131618  c  t 0.0705 -0.0198 0.0335 0.553600 367592
3 rs141242758  c  t 0.1306 -0.0518 0.0235 0.027170 367592
4  rs79010578  a  t 0.1530 -0.0691 0.0258 0.007437 367592
5  rs61770167  t  c 0.0365 -0.1608 0.0832 0.053350 367592
6   rs3094315  a  g 0.8310  0.0521 0.0219 0.017500 367592
```

I get this error message when I try to upload it. 
![image](https://github.com/user-attachments/assets/d131bbb3-5469-4331-80ff-a24a81030069)

I saved the text file with this line of code (below), wondering if it's to do with the tab delimited format, but I still get the error message. Any suggestions?
`write.table(cd, "cd_cojo_smr_portal.txt", sep = "\t", row.names = F)`

**Comment by rikomiko** [comment]
Sorry, I did not realise that R removes the quotes from the text file written using `write.table`. I had to include `quote = F` and `sep = "\t"` and I was able to upload the file.

**Comment by YaJoo** [comment]
Hi rikomiko,

We recommend you to upload your GWAS summary file with right headers:
e.g. frq --> freq

`SNP A1 A2    frq       b     se        P      N`
to
`SNP    A1  A2  freq    b   se  p   n`

We will fix the compatibility issue in our next updated published version.

Best wishes,
Yazhou

**Comment by rikomiko** [comment]
Hi Yazhou,

Thank you for your recommendation! I made the changes. I also changed the code to exclude the quotes and the analysis could run.

Kind regards,
Rika
